### ISSUE TITLE
Bug: Last stock removal

### ISSUE THREAD

**Issue by zubhav** [Prubby/covid-19-vs-markets#60]
When you hover over the last stock symbol and remove it, the graph stays with the highlighted line on it

**Comment by zubhav** [comment]
![Screen Shot 2020-03-31 at 01 07 11](https://user-images.githubusercontent.com/9058689/77973401-fb774480-72eb-11ea-8ef8-85b0583f3d0f.png)

**Comment by pranjaljately** [comment]
Update: This happens regardless of the hover. The map does graph does not update when there are no stocks.
